services:
  mysql-db:
    image: mysql:8.0
    container_name: sicr-database
    restart: always
    # FORÇA O PADRÃO DE SENHA COMPATÍVEL
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: votacao_db
      MYSQL_USER: uservotacao
      MYSQL_PASSWORD: passvotacao123
      MYSQL_ROOT_PASSWORD: passroot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  mysql_data: